# Generated by Django 5.1.1 on 2024-09-30 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_for_everyone', models.BooleanField(default=False, verbose_name='Is for everyone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('sent_time', models.DateTimeField(verbose_name='Sent time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'NotificationUser',
                'verbose_name_plural': 'NotificationUsers',
            },
        ),
    ]
