# Generated by Django 5.1.1 on 2024-10-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_userfcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notification_users', to='notification.notification', verbose_name='Notification'),
            preserve_default=False,
        ),
    ]
