# Generated by Django 5.1.1 on 2024-10-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationuser_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent time'),
        ),
    ]
